
services:
  kitchen-app:
    # 1. THE IMAGE
    image: philippbtz/kitchen-helper:latest

    # 2. THE PORTS
    ports:
      - "80:80"

    # 3. THE STORAGE (PERSISTENCE)
    volumes:
      - ./kitchen_data:/app/.local

    # 4. THE SAFETY NET
    restart: always

    # 5. ENVIRONMENT VARIABLES
    environment:
      - PRODUCTION=true